#ifndef DG_CAPI_H
#define DG_CAPI_H

#pragma once

/* Generated by cbindgen; do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI status returned by every fallible C entry point.
 */
typedef enum DgStatus {
  Ok = 0,
  Again = 1,
  EndOfStream = 2,
  InvalidArgument = -1,
  NullPointer = -2,
  InvalidHandle = -3,
  ParseError = -4,
  NotBuilt = -5,
  RuntimeError = -6,
  Unsupported = -7,
  Panic = -8,
  InternalError = -9,
} DgStatus;

/**
 * Graph serialization format.
 */
typedef enum DgGraphFormat {
  Yaml = 0,
  Json = 1,
  Toml = 2,
} DgGraphFormat;

/**
 * Backend family for direct backend lifecycle operations.
 */
typedef enum DgBackendKind {
  Mock = 0,
  OpenVino = 1,
  Rknn = 2,
  TensorRt = 3,
  Sophon = 4,
} DgBackendKind;

/**
 * Logical device family.
 */
typedef enum DgDeviceKind {
  Cpu = 0,
  IntelGpu = 1,
  IntelNpu = 2,
  CudaGpu = 3,
  RknnNpu = 4,
  SophonTpu = 5,
} DgDeviceKind;

/**
 * Supported tensor element types.
 */
typedef enum DgDataType {
  U8 = 0,
  U16 = 1,
  I4 = 2,
  I8 = 3,
  I16 = 4,
  F4 = 5,
  F8 = 6,
  F16 = 7,
  Bf16 = 8,
  F32 = 9,
  F64 = 10,
  U32 = 11,
  I32 = 12,
  U64 = 13,
  I64 = 14,
} DgDataType;

/**
 * Tensor layout.
 */
typedef enum DgDataFormat {
  Auto = 0,
  N = 1,
  Nc = 2,
  Nchw = 3,
  Nhwc = 4,
  Nc4hw = 5,
  Nc8hw = 6,
  Ncdhw = 7,
  Oihw = 8,
} DgDataFormat;

/**
 * Imported external memory domain.
 */
typedef enum DgMemoryDomain {
  Host = 0,
  DmaBuf = 1,
  DrmPrime = 2,
  VaapiSurface = 3,
  CudaDevice = 4,
  MppBuffer = 5,
  SophonDevice = 6,
  Opaque = 7,
} DgMemoryDomain;

/**
 * Opaque direct inference backend handle.
 */
typedef struct DgBackend DgBackend;

/**
 * Opaque buffer handle.
 */
typedef struct DgBuffer DgBuffer;

/**
 * Opaque graph engine handle.
 */
typedef struct DgEngine DgEngine;

/**
 * Opaque tensor handle.
 */
typedef struct DgTensor DgTensor;

/**
 * Runtime capabilities returned by a direct backend.
 */
typedef struct DgBackendCapabilities {
  size_t device_count;
  enum DgDeviceKind devices[8];
  size_t precision_count;
  enum DgDataType precisions[16];
} DgBackendCapabilities;

/**
 * Fixed-size tensor metadata returned by direct backend queries.
 */
typedef struct DgTensorInfo {
  enum DgDataType dtype;
  enum DgDataFormat format;
  enum DgDeviceKind device;
  size_t rank;
  size_t shape[8];
} DgTensorInfo;

/**
 * Returns the most recent error for the calling thread.
 */
const char *dg_last_error(void);

/**
 * Returns the package version as a static UTF-8 C string.
 */
const char *dg_version(void);

/**
 * Creates an engine handle.
 */
enum DgStatus dg_engine_create(struct DgEngine **out);

/**
 * Frees an engine handle. Null is accepted.
 */
void dg_engine_free(struct DgEngine *engine);

/**
 * Loads a graph specification from a UTF-8 string.
 */
enum DgStatus dg_engine_load_string(struct DgEngine *engine,
                                    enum DgGraphFormat format,
                                    const char *content);

/**
 * Loads a graph specification from a UTF-8 path.
 */
enum DgStatus dg_engine_load_file(struct DgEngine *engine, const char *path);

/**
 * Reloads a graph specification from a UTF-8 string.
 *
 * A built graph is updated in place and remains ready to run. Reload is rejected while inputs
 * are pending so that queued data is never silently interpreted by a changed graph.
 */
enum DgStatus dg_engine_reload_string(struct DgEngine *engine,
                                      enum DgGraphFormat format,
                                      const char *content);

/**
 * Reloads a graph specification from a UTF-8 path.
 *
 * A built graph is updated in place and remains ready to run. Reload is rejected while inputs
 * are pending so that queued data is never silently interpreted by a changed graph.
 */
enum DgStatus dg_engine_reload_file(struct DgEngine *engine, const char *path);

/**
 * Computes node and connection changes against a UTF-8 graph specification.
 */
enum DgStatus dg_engine_diff_string(const struct DgEngine *engine,
                                    enum DgGraphFormat format,
                                    const char *content,
                                    size_t *out_added_nodes,
                                    size_t *out_removed_nodes,
                                    size_t *out_updated_nodes,
                                    size_t *out_added_connections,
                                    size_t *out_removed_connections);

/**
 * Computes node and connection changes against a UTF-8 graph file.
 */
enum DgStatus dg_engine_diff_file(const struct DgEngine *engine,
                                  const char *path,
                                  size_t *out_added_nodes,
                                  size_t *out_removed_nodes,
                                  size_t *out_updated_nodes,
                                  size_t *out_added_connections,
                                  size_t *out_removed_connections);

/**
 * Adds a node programmatically. `params_json` may be null for an empty object.
 */
enum DgStatus dg_engine_add_node(struct DgEngine *engine,
                                 const char *name,
                                 const char *kind,
                                 const char *params_json);

/**
 * Removes a node by name and its incident connections.
 */
enum DgStatus dg_engine_remove_node(struct DgEngine *engine, const char *name);

/**
 * Adds a graph edge in `source.port -> destination.port` form.
 */
enum DgStatus dg_engine_connect(struct DgEngine *engine, const char *connection);

/**
 * Removes a graph edge.
 */
enum DgStatus dg_engine_disconnect(struct DgEngine *engine, const char *connection);

/**
 * Validates and builds the current graph specification.
 */
enum DgStatus dg_engine_build(struct DgEngine *engine);

/**
 * Runs the built graph with pending inputs and stores sink outputs for polling.
 */
enum DgStatus dg_engine_run(struct DgEngine *engine);

/**
 * Creates and initializes a backend without constructing a graph.
 */
enum DgStatus dg_backend_create(enum DgBackendKind kind,
                                const uint8_t *model_data,
                                size_t model_length,
                                const char *options_json,
                                struct DgBackend **out);

/**
 * Frees a direct backend handle. Null is accepted.
 */
void dg_backend_free(struct DgBackend *backend);

/**
 * Returns the number of backend inputs and outputs.
 */
enum DgStatus dg_backend_io_counts(const struct DgBackend *backend,
                                   size_t *out_inputs,
                                   size_t *out_outputs);

/**
 * Queries runtime device and precision capabilities.
 */
enum DgStatus dg_backend_capabilities(const struct DgBackend *backend,
                                      struct DgBackendCapabilities *out);

/**
 * Queries one input or output tensor description.
 */
enum DgStatus dg_backend_tensor_info(const struct DgBackend *backend,
                                     bool output,
                                     size_t index,
                                     struct DgTensorInfo *out);

/**
 * Runs direct backend inference over caller-owned tensor handles.
 */
enum DgStatus dg_backend_run(struct DgBackend *backend,
                             const struct DgTensor *const *inputs,
                             size_t input_count,
                             struct DgTensor **outputs,
                             size_t output_capacity,
                             size_t *out_count);

/**
 * Creates a host tensor from a caller-owned byte array.
 */
enum DgStatus dg_tensor_create(const uint8_t *data,
                               size_t length,
                               const size_t *shape,
                               size_t rank,
                               enum DgDataType dtype,
                               enum DgDataFormat format,
                               enum DgDeviceKind device,
                               struct DgTensor **out);

/**
 * Creates a tensor backed by an imported external buffer.
 */
enum DgStatus dg_tensor_create_external(int fd,
                                        uint64_t raw,
                                        enum DgMemoryDomain domain,
                                        size_t size_bytes,
                                        const size_t *shape,
                                        size_t rank,
                                        enum DgDataType dtype,
                                        enum DgDataFormat format,
                                        enum DgDeviceKind device,
                                        struct DgTensor **out);

/**
 * Frees a tensor handle. Null is accepted.
 */
void dg_tensor_free(struct DgTensor *tensor);

/**
 * Returns a copied tensor byte snapshot.
 */
enum DgStatus dg_tensor_data(const struct DgTensor *tensor,
                             const uint8_t **out_data,
                             size_t *out_length);

/**
 * Pushes one tensor into the built graph.
 */
enum DgStatus dg_engine_push(struct DgEngine *engine, const struct DgTensor *tensor);

/**
 * Polls one output tensor. `Again` means the queue is empty.
 */
enum DgStatus dg_engine_poll(struct DgEngine *engine, struct DgTensor **out);

/**
 * Imports an external buffer handle without dereferencing the external address.
 */
enum DgStatus dg_buffer_import_external(int fd,
                                        uint64_t raw,
                                        enum DgMemoryDomain domain,
                                        enum DgDeviceKind device,
                                        size_t size_bytes,
                                        struct DgBuffer **out);

/**
 * Returns the logical size of an imported buffer.
 */
enum DgStatus dg_buffer_size(const struct DgBuffer *buffer, size_t *out_size);

/**
 * Frees an external buffer handle.
 */
void dg_buffer_free(struct DgBuffer *buffer);

#endif  /* DG_CAPI_H */
