//! Safe TensorRT adapter built on the C/C++ shim generated by `build.rs`.
//!
//! All `unsafe` is confined to the RAII wrappers in [`ffi`]; the backend
//! itself only manipulates safe handles.

use std::fs;

use dg_core::{CpuDevice, DataFormat, DataType, Shape, Tensor};
use dg_runtime::{
    backend_capabilities, BackendConfig, BackendDescriptor, BackendKind, BackendOptions, Error,
    InferBackend, ModelSource, Result, RuntimeCapabilities, RuntimeOption, TensorInfo,
    TensorRtOptions,
};
use serde::Deserialize;
use tracing::trace;

#[cfg(feature = "backend")]
use dg_tensorrt_sys as sys;

use crate::convert::{
    dims_to_shape, engine_dims_to_shape, shape_matches_engine_dims, shape_to_dims,
    trt_dtype_to_datatype, validate_runtime_option,
};
use ffi::{Context, CudaStream, DeviceBuffer, Engine, Runtime};

#[cfg(not(feature = "backend"))]
use crate::mock_sys as sys;

#[cfg(feature = "backend")]
pub const fn backend_enabled() -> bool {
    true
}

/// RAII wrappers around the shim handles. This module is the only place in
/// the crate (besides the test-only mock) that touches raw pointers.
mod ffi {
    use std::ffi::{c_void, CString};
    use std::ptr::NonNull;

    use dg_runtime::{Error, Result};

    use super::sys;
    use crate::convert::TRT_MAX_DIMS;

    /// Owned `nvinfer1::IRuntime` handle.
    pub(super) struct Runtime {
        raw: NonNull<sys::trt_runtime_handle>,
    }

    impl Runtime {
        pub(super) fn create() -> Result<Self> {
            // SAFETY: trt_runtime_create takes no arguments and returns either
            // a valid heap-allocated handle or null.
            let raw = unsafe { sys::trt_runtime_create() };
            NonNull::new(raw).map(|raw| Self { raw }).ok_or_else(|| {
                Error::BackendUnavailable("trt_runtime_create returned null".to_string())
            })
        }
    }

    // SAFETY: the handle owns its `nvinfer1::IRuntime` exclusively and
    // TensorRT allows moving runtime objects across threads.
    unsafe impl Send for Runtime {}

    impl Drop for Runtime {
        fn drop(&mut self) {
            // SAFETY: `raw` was produced by trt_runtime_create and is
            // destroyed exactly once here.
            unsafe { sys::trt_runtime_destroy(self.raw.as_ptr()) };
        }
    }

    /// Owned `nvinfer1::ICudaEngine` handle. Must not outlive the `Runtime`
    /// that deserialized it; `TensorRtBackend` guarantees this by field
    /// declaration order.
    pub(super) struct Engine {
        raw: NonNull<sys::trt_engine_handle>,
    }

    impl Engine {
        pub(super) fn deserialize(runtime: &Runtime, model: &[u8]) -> Result<Self> {
            // SAFETY: `runtime` is a live handle and `model` outlives the
            // call; the shim copies what it needs during deserialization.
            let raw = unsafe {
                sys::trt_runtime_deserialize_engine(
                    runtime.raw.as_ptr(),
                    model.as_ptr() as *const c_void,
                    model.len(),
                )
            };
            NonNull::new(raw).map(|raw| Self { raw }).ok_or_else(|| {
                Error::BackendUnavailable(
                    "trt_runtime_deserialize_engine failed: not a valid TensorRT engine"
                        .to_string(),
                )
            })
        }

        pub(super) fn num_io(&self) -> Result<usize> {
            // SAFETY: `raw` is a live engine handle.
            let count = unsafe { sys::trt_engine_num_io(self.raw.as_ptr()) };
            usize::try_from(count)
                .map_err(|_| Error::Backend("trt_engine_num_io failed".to_string()))
        }

        pub(super) fn io_name(&self, index: usize) -> Result<String> {
            let index = to_c_index(index)?;
            // SAFETY: `raw` is a live engine handle; the returned pointer, if
            // non-null, references a NUL-terminated string owned by the
            // engine which outlives this call.
            let name = unsafe { sys::trt_engine_io_name(self.raw.as_ptr(), index) };
            if name.is_null() {
                return Err(Error::Backend(format!(
                    "trt_engine_io_name failed for binding {index}"
                )));
            }
            // SAFETY: `name` is non-null and NUL-terminated (checked above).
            let name = unsafe { std::ffi::CStr::from_ptr(name) };
            Ok(name.to_string_lossy().into_owned())
        }

        pub(super) fn io_is_input(&self, index: usize) -> Result<bool> {
            let index = to_c_index(index)?;
            // SAFETY: `raw` is a live engine handle.
            Ok(unsafe { sys::trt_engine_io_is_input(self.raw.as_ptr(), index) } != 0)
        }

        pub(super) fn io_dtype(&self, index: usize) -> Result<i32> {
            let index = to_c_index(index)?;
            // SAFETY: `raw` is a live engine handle.
            let dtype = unsafe { sys::trt_engine_io_dtype(self.raw.as_ptr(), index) };
            if dtype < 0 {
                return Err(Error::Backend(format!(
                    "trt_engine_io_dtype failed for binding {index}"
                )));
            }
            Ok(dtype)
        }

        pub(super) fn io_dims(&self, index: usize) -> Result<Vec<i64>> {
            let index = to_c_index(index)?;
            let mut dims = [0i64; TRT_MAX_DIMS];
            // SAFETY: `raw` is a live engine handle and `dims` provides
            // TRT_MAX_DIMS writable slots as advertised via `max_rank`.
            let rank = unsafe {
                sys::trt_engine_io_shape(self.raw.as_ptr(), index, dims.as_mut_ptr(), dims.len())
            };
            let rank = usize::try_from(rank).map_err(|_| {
                Error::Backend(format!("trt_engine_io_shape failed for binding {index}"))
            })?;
            Ok(dims[..rank].to_vec())
        }

        pub(super) fn create_context(&self) -> Result<Context> {
            // SAFETY: `raw` is a live engine handle.
            let raw = unsafe { sys::trt_engine_create_context(self.raw.as_ptr()) };
            NonNull::new(raw).map(|raw| Context { raw }).ok_or_else(|| {
                Error::BackendUnavailable("trt_engine_create_context failed".to_string())
            })
        }
    }

    // SAFETY: the handle owns its `nvinfer1::ICudaEngine` exclusively and
    // TensorRT allows moving engine objects across threads.
    unsafe impl Send for Engine {}

    impl Drop for Engine {
        fn drop(&mut self) {
            // SAFETY: `raw` was produced by trt_runtime_deserialize_engine
            // and is destroyed exactly once here.
            unsafe { sys::trt_engine_destroy(self.raw.as_ptr()) };
        }
    }

    /// Owned `nvinfer1::IExecutionContext` handle. Must not outlive its
    /// `Engine`; `TensorRtBackend` guarantees this by field declaration order.
    pub(super) struct Context {
        raw: NonNull<sys::trt_context_handle>,
    }

    impl Context {
        pub(super) fn set_input_shape(&mut self, name: &str, dims: &[i64]) -> Result<()> {
            let cname = to_cname(name)?;
            // SAFETY: `raw` is a live context handle; `cname` and `dims`
            // outlive the call and `dims.len()` matches the buffer length.
            let ok = unsafe {
                sys::trt_context_set_input_shape(
                    self.raw.as_ptr(),
                    cname.as_ptr(),
                    dims.as_ptr(),
                    dims.len(),
                )
            };
            if ok == 0 {
                return Err(Error::Backend(format!(
                    "TensorRT rejected shape {dims:?} for input {name}"
                )));
            }
            Ok(())
        }

        pub(super) fn tensor_shape(&self, name: &str) -> Result<Vec<i64>> {
            let cname = to_cname(name)?;
            let mut dims = [0i64; TRT_MAX_DIMS];
            // SAFETY: `raw` is a live context handle and `dims` provides
            // TRT_MAX_DIMS writable slots as advertised via `max_rank`.
            let rank = unsafe {
                sys::trt_context_get_tensor_shape(
                    self.raw.as_ptr(),
                    cname.as_ptr(),
                    dims.as_mut_ptr(),
                    dims.len(),
                )
            };
            let rank = usize::try_from(rank).map_err(|_| {
                Error::Backend(format!("failed to resolve shape for tensor {name}"))
            })?;
            Ok(dims[..rank].to_vec())
        }

        pub(super) fn set_tensor_address(
            &mut self,
            name: &str,
            buffer: &mut DeviceBuffer,
        ) -> Result<()> {
            let cname = to_cname(name)?;
            // SAFETY: `raw` is a live context handle and `buffer` owns a
            // device allocation that the backend keeps alive until after
            // stream synchronization.
            let ok = unsafe {
                sys::trt_context_set_tensor_address(
                    self.raw.as_ptr(),
                    cname.as_ptr(),
                    buffer.as_mut_ptr(),
                )
            };
            if ok == 0 {
                return Err(Error::Backend(format!(
                    "trt_context_set_tensor_address failed for tensor {name}"
                )));
            }
            Ok(())
        }

        pub(super) fn enqueue(&mut self, stream: &CudaStream) -> Result<()> {
            // SAFETY: `raw` is a live context handle and `stream` owns a live
            // CUDA stream.
            let ok = unsafe { sys::trt_context_enqueue(self.raw.as_ptr(), stream.raw.as_ptr()) };
            if ok == 0 {
                return Err(Error::Backend(
                    "trt_context_enqueue failed to launch inference".to_string(),
                ));
            }
            Ok(())
        }
    }

    // SAFETY: the handle owns its `nvinfer1::IExecutionContext` exclusively;
    // a context is used by one thread at a time (`&mut self` methods).
    unsafe impl Send for Context {}

    impl Drop for Context {
        fn drop(&mut self) {
            // SAFETY: `raw` was produced by trt_engine_create_context and is
            // destroyed exactly once here.
            unsafe { sys::trt_context_destroy(self.raw.as_ptr()) };
        }
    }

    /// Owned CUDA stream.
    pub(super) struct CudaStream {
        raw: NonNull<c_void>,
    }

    impl CudaStream {
        pub(super) fn create() -> Result<Self> {
            // SAFETY: trt_cuda_stream_create takes no arguments and returns
            // either a valid stream or null.
            let raw = unsafe { sys::trt_cuda_stream_create() };
            NonNull::new(raw).map(|raw| Self { raw }).ok_or_else(|| {
                Error::BackendUnavailable("failed to create CUDA stream".to_string())
            })
        }

        pub(super) fn synchronize(&self) -> Result<()> {
            // SAFETY: `raw` is a live stream handle.
            let ok = unsafe { sys::trt_cuda_stream_synchronize(self.raw.as_ptr()) };
            if ok == 0 {
                return Err(Error::Backend(
                    "CUDA stream synchronization failed".to_string(),
                ));
            }
            Ok(())
        }
    }

    impl Drop for CudaStream {
        fn drop(&mut self) {
            // SAFETY: `raw` was produced by trt_cuda_stream_create and is
            // destroyed exactly once here.
            unsafe { sys::trt_cuda_stream_destroy(self.raw.as_ptr()) };
        }
    }

    /// Owned CUDA device allocation.
    pub(super) struct DeviceBuffer {
        raw: NonNull<c_void>,
        len: usize,
        owned: bool,
    }

    impl DeviceBuffer {
        pub(super) fn alloc(len: usize) -> Result<Self> {
            // SAFETY: trt_cuda_malloc returns either a device allocation of
            // at least `len` bytes or null.
            let raw = unsafe { sys::trt_cuda_malloc(len) };
            NonNull::new(raw)
                .map(|raw| Self {
                    raw,
                    len,
                    owned: true,
                })
                .ok_or_else(|| {
                    Error::BackendUnavailable(format!(
                        "failed to allocate {len} bytes of CUDA device memory"
                    ))
                })
        }

        pub(super) fn from_external_ptr(raw: u64, len: usize) -> Result<Self> {
            let raw = usize::try_from(raw)
                .map_err(|_| Error::Backend("CUDA pointer does not fit usize".to_string()))?;
            let raw = NonNull::new(raw as *mut c_void)
                .ok_or_else(|| Error::Backend("external CUDA pointer is null".to_string()))?;
            Ok(Self {
                raw,
                len,
                owned: false,
            })
        }

        pub(super) fn as_mut_ptr(&mut self) -> *mut c_void {
            self.raw.as_ptr()
        }

        pub(super) fn copy_from_host(&mut self, data: &[u8]) -> Result<()> {
            if data.len() > self.len {
                return Err(Error::Backend(
                    "host buffer exceeds device allocation".to_string(),
                ));
            }
            // SAFETY: `raw` points at `self.len` device bytes and `data`
            // provides `data.len() <= self.len` readable host bytes.
            let ok = unsafe {
                sys::trt_cuda_memcpy_h2d(
                    self.raw.as_ptr(),
                    data.as_ptr() as *const c_void,
                    data.len(),
                )
            };
            if ok == 0 {
                return Err(Error::Backend(
                    "CUDA host-to-device copy failed".to_string(),
                ));
            }
            Ok(())
        }

        pub(super) fn copy_to_host(&self, data: &mut [u8]) -> Result<()> {
            if data.len() > self.len {
                return Err(Error::Backend(
                    "host buffer exceeds device allocation".to_string(),
                ));
            }
            // SAFETY: `raw` points at `self.len` device bytes and `data`
            // provides `data.len() <= self.len` writable host bytes.
            let ok = unsafe {
                sys::trt_cuda_memcpy_d2h(
                    data.as_mut_ptr() as *mut c_void,
                    self.raw.as_ptr(),
                    data.len(),
                )
            };
            if ok == 0 {
                return Err(Error::Backend(
                    "CUDA device-to-host copy failed".to_string(),
                ));
            }
            Ok(())
        }
    }

    impl Drop for DeviceBuffer {
        fn drop(&mut self) {
            // SAFETY: `raw` was produced by trt_cuda_malloc and is freed
            // exactly once here.
            if self.owned {
                unsafe { sys::trt_cuda_free(self.raw.as_ptr()) };
            }
        }
    }

    /// Returns the number of visible CUDA devices.
    pub(super) fn cuda_device_count() -> Result<usize> {
        // SAFETY: trt_cuda_device_count takes no arguments.
        let count = unsafe { sys::trt_cuda_device_count() };
        usize::try_from(count)
            .map_err(|_| Error::BackendUnavailable("failed to query CUDA device count".to_string()))
    }

    /// Selects the active CUDA device for this thread.
    pub(super) fn cuda_set_device(device: u32) -> Result<()> {
        let device_index = std::os::raw::c_int::try_from(device)
            .map_err(|_| Error::InvalidOption(format!("CUDA device id {device} overflows")))?;
        // SAFETY: trt_cuda_set_device only reads its integer argument.
        let ok = unsafe { sys::trt_cuda_set_device(device_index) };
        if ok == 0 {
            return Err(Error::BackendUnavailable(format!(
                "failed to select CUDA device {device}"
            )));
        }
        Ok(())
    }

    fn to_c_index(index: usize) -> Result<std::os::raw::c_int> {
        std::os::raw::c_int::try_from(index)
            .map_err(|_| Error::InvalidOption(format!("binding index {index} overflows")))
    }

    fn to_cname(name: &str) -> Result<CString> {
        CString::new(name)
            .map_err(|_| Error::Backend(format!("tensor name contains NUL byte: {name}")))
    }
}

struct IoBinding {
    name: String,
    dtype: DataType,
    engine_dims: Vec<i64>,
}

pub struct TensorRtBackend {
    // Field order matters: `context` must drop before `engine`, which must
    // drop before `runtime`.
    context: Option<Context>,
    engine: Option<Engine>,
    runtime: Option<Runtime>,
    options: TensorRtOptions,
    inputs: Vec<IoBinding>,
    outputs: Vec<IoBinding>,
    input_infos: Vec<TensorInfo>,
    output_infos: Vec<TensorInfo>,
    last_copy_count: usize,
}

impl TensorRtBackend {
    fn new() -> Self {
        Self {
            context: None,
            engine: None,
            runtime: None,
            options: TensorRtOptions::default(),
            inputs: Vec::new(),
            outputs: Vec::new(),
            input_infos: Vec::new(),
            output_infos: Vec::new(),
            last_copy_count: 0,
        }
    }

    fn load_model(source: &ModelSource) -> Result<Vec<u8>> {
        match source {
            ModelSource::File(path) => fs::read(path).map_err(|err| {
                Error::BackendUnavailable(format!(
                    "failed to read TensorRT engine file {}: {err}",
                    path.display()
                ))
            }),
            ModelSource::Bytes(bytes) => Ok(bytes.clone()),
        }
    }

    fn select_device(options: &TensorRtOptions) -> Result<()> {
        let device_count = ffi::cuda_device_count()?;
        if device_count == 0 {
            return Err(Error::BackendUnavailable(
                "no CUDA devices are visible to the TensorRT backend".to_string(),
            ));
        }
        if let Some(device_id) = options.device_id {
            if usize::try_from(device_id)
                .map(|id| id >= device_count)
                .unwrap_or(true)
            {
                return Err(Error::UnsupportedDevice(dg_core::DeviceKind::CudaGpu));
            }
            ffi::cuda_set_device(device_id)?;
        }
        Ok(())
    }

    fn inspect_bindings(engine: &Engine) -> Result<(Vec<IoBinding>, Vec<IoBinding>)> {
        let mut inputs = Vec::new();
        let mut outputs = Vec::new();
        for index in 0..engine.num_io()? {
            let name = engine.io_name(index)?;
            let dtype = trt_dtype_to_datatype(engine.io_dtype(index)?)?;
            let engine_dims = engine.io_dims(index)?;
            let binding = IoBinding {
                name,
                dtype,
                engine_dims,
            };
            if engine.io_is_input(index)? {
                inputs.push(binding);
            } else {
                outputs.push(binding);
            }
        }
        if inputs.is_empty() {
            return Err(Error::Backend(
                "TensorRT engine exposes no input tensors".to_string(),
            ));
        }
        if outputs.is_empty() {
            return Err(Error::Backend(
                "TensorRT engine exposes no output tensors".to_string(),
            ));
        }
        Ok((inputs, outputs))
    }

    fn binding_infos(bindings: &[IoBinding]) -> Result<Vec<TensorInfo>> {
        bindings
            .iter()
            .map(|binding| {
                let (shape, _) = engine_dims_to_shape(&binding.engine_dims, &binding.name)?;
                Ok(TensorInfo::new(shape, binding.dtype)
                    .with_name(binding.name.clone())
                    .with_layout(DataFormat::Auto))
            })
            .collect()
    }

    fn validate_inputs(&self, inputs: &[Tensor]) -> Result<()> {
        if inputs.len() != self.inputs.len() {
            return Err(Error::InvalidOption(format!(
                "TensorRT engine expects {} inputs, got {}",
                self.inputs.len(),
                inputs.len()
            )));
        }
        for (tensor, binding) in inputs.iter().zip(&self.inputs) {
            if tensor.desc().dtype() != binding.dtype {
                return Err(Error::InvalidOption(format!(
                    "input {} expects dtype {:?}, got {:?}",
                    binding.name,
                    binding.dtype,
                    tensor.desc().dtype()
                )));
            }
            if !shape_matches_engine_dims(tensor.desc().shape(), &binding.engine_dims) {
                return Err(Error::InvalidOption(format!(
                    "input {} shape {:?} is incompatible with engine dims {:?}",
                    binding.name,
                    tensor.desc().shape().dims(),
                    binding.engine_dims
                )));
            }
            let expected_bytes = binding
                .dtype
                .storage_bytes_for_shape(tensor.desc().shape())?;
            if tensor.buffer().len() != expected_bytes {
                return Err(Error::InvalidOption(format!(
                    "input {} requires {expected_bytes} bytes, buffer holds {}",
                    binding.name,
                    tensor.buffer().len()
                )));
            }
        }
        Ok(())
    }

    fn refresh_output_infos(&mut self) -> Result<()> {
        let Some(context) = self.context.as_ref() else {
            return Err(Error::InvalidOption(
                "TensorRT backend is not initialized".to_string(),
            ));
        };
        let mut output_infos = Vec::with_capacity(self.outputs.len());
        for binding in &self.outputs {
            let dims = context.tensor_shape(&binding.name)?;
            let shape = dims_to_shape(&dims, &binding.name)?;
            output_infos.push(
                TensorInfo::new(shape, binding.dtype)
                    .with_name(binding.name.clone())
                    .with_layout(DataFormat::Auto),
            );
        }
        self.output_infos = output_infos;
        Ok(())
    }
}

impl InferBackend for TensorRtBackend {
    fn kind(&self) -> BackendKind {
        BackendKind::TensorRt
    }

    fn probe_capabilities(&self) -> Result<RuntimeCapabilities> {
        let mut capabilities = backend_capabilities(BackendKind::TensorRt)
            .map(RuntimeCapabilities::from_static)
            .ok_or_else(|| {
                Error::BackendUnavailable("TensorRT capabilities unavailable".to_string())
            })?;
        capabilities.device_count = ffi::cuda_device_count()?;
        if capabilities.device_count == 0 {
            capabilities.devices.clear();
        }
        Ok(capabilities)
    }

    fn init(&mut self, option: &RuntimeOption) -> Result<()> {
        trace!("initializing TensorRT backend");
        validate_runtime_option(option)?;
        let BackendOptions::TensorRt(tensorrt) = &option.backend_options else {
            return Err(Error::InvalidOption(
                "TensorRT backend requires TensorRT backend options".to_string(),
            ));
        };
        Self::select_device(tensorrt)?;
        self.options = tensorrt.clone();

        let model = Self::load_model(&option.model_source)?;
        let runtime = Runtime::create()?;
        let engine = Engine::deserialize(&runtime, &model)?;
        let context = engine.create_context()?;

        let (inputs, outputs) = Self::inspect_bindings(&engine)?;
        self.input_infos = Self::binding_infos(&inputs)?;
        self.output_infos = Self::binding_infos(&outputs)?;
        self.inputs = inputs;
        self.outputs = outputs;
        self.context = Some(context);
        self.engine = Some(engine);
        self.runtime = Some(runtime);
        Ok(())
    }

    fn reshape(&mut self, input_shapes: &[Shape]) -> Result<()> {
        if input_shapes.len() != self.inputs.len() {
            return Err(Error::InvalidOption(format!(
                "TensorRT reshape expects {} shapes, got {}",
                self.inputs.len(),
                input_shapes.len()
            )));
        }
        let Some(context) = self.context.as_mut() else {
            return Err(Error::InvalidOption(
                "TensorRT backend is not initialized".to_string(),
            ));
        };
        for (shape, binding) in input_shapes.iter().zip(&self.inputs) {
            if !shape_matches_engine_dims(shape, &binding.engine_dims) {
                return Err(Error::InvalidOption(format!(
                    "input {} shape {:?} is incompatible with engine dims {:?}",
                    binding.name,
                    shape.dims(),
                    binding.engine_dims
                )));
            }
            let dims = shape_to_dims(shape, &binding.name)?;
            context.set_input_shape(&binding.name, &dims)?;
        }
        self.input_infos = input_shapes
            .iter()
            .zip(&self.inputs)
            .map(|(shape, binding)| {
                TensorInfo::new(shape.clone(), binding.dtype)
                    .with_name(binding.name.clone())
                    .with_layout(DataFormat::Auto)
            })
            .collect();
        self.refresh_output_infos()
    }

    fn input_count(&self) -> usize {
        self.input_infos.len()
    }

    fn output_count(&self) -> usize {
        self.output_infos.len()
    }

    fn input_info(&self, index: usize) -> Result<&TensorInfo> {
        self.input_infos
            .get(index)
            .ok_or_else(|| Error::InvalidOption(format!("input index out of range: {index}")))
    }

    fn output_info(&self, index: usize) -> Result<&TensorInfo> {
        self.output_infos
            .get(index)
            .ok_or_else(|| Error::InvalidOption(format!("output index out of range: {index}")))
    }

    fn input_infos(&self) -> &[TensorInfo] {
        &self.input_infos
    }

    fn output_infos(&self) -> &[TensorInfo] {
        &self.output_infos
    }

    fn run(&mut self, inputs: &[Tensor]) -> Result<Vec<Tensor>> {
        self.last_copy_count = 0;
        self.validate_inputs(inputs)?;
        let Some(context) = self.context.as_mut() else {
            return Err(Error::InvalidOption(
                "TensorRT backend is not initialized".to_string(),
            ));
        };

        let stream = CudaStream::create()?;
        let mut input_buffers = Vec::with_capacity(self.inputs.len());
        for (tensor, binding) in inputs.iter().zip(&self.inputs) {
            let dims = shape_to_dims(tensor.desc().shape(), &binding.name)?;
            context.set_input_shape(&binding.name, &dims)?;
            let byte_len = binding
                .dtype
                .storage_bytes_for_shape(tensor.desc().shape())?;
            let mut buffer = if tensor.buffer().domain() == dg_core::MemoryDomain::CudaDevice {
                let external = tensor.buffer().external();
                if external.raw == 0 {
                    return Err(Error::Backend(
                        "CUDA device buffer is missing an external pointer".to_string(),
                    ));
                }
                DeviceBuffer::from_external_ptr(external.raw, byte_len)?
            } else {
                self.last_copy_count = self.last_copy_count.saturating_add(1);
                let bytes = tensor.buffer().try_read_bytes()?;
                let mut buffer = DeviceBuffer::alloc(bytes.len())?;
                buffer.copy_from_host(&bytes)?;
                buffer
            };
            context.set_tensor_address(&binding.name, &mut buffer)?;
            input_buffers.push(buffer);
        }

        let mut output_buffers = Vec::with_capacity(self.outputs.len());
        let mut output_shapes = Vec::with_capacity(self.outputs.len());
        for binding in &self.outputs {
            let dims = context.tensor_shape(&binding.name)?;
            let shape = dims_to_shape(&dims, &binding.name)?;
            let byte_len = binding.dtype.storage_bytes_for_shape(&shape)?;
            let mut buffer = DeviceBuffer::alloc(byte_len)?;
            context.set_tensor_address(&binding.name, &mut buffer)?;
            output_buffers.push(buffer);
            output_shapes.push(shape);
        }

        context.enqueue(&stream)?;
        stream.synchronize()?;
        trace!(
            backend = "tensorrt",
            copy_count = self.last_copy_count,
            path = if self.last_copy_count == 0 {
                "zero_copy"
            } else {
                "staging"
            },
            "TensorRT input binding completed"
        );

        let device = CpuDevice::new();
        let mut outputs = Vec::with_capacity(self.outputs.len());
        for ((binding, buffer), shape) in
            self.outputs.iter().zip(&output_buffers).zip(output_shapes)
        {
            let byte_len = binding.dtype.storage_bytes_for_shape(&shape)?;
            let mut host = vec![0u8; byte_len];
            buffer.copy_to_host(&mut host)?;
            let output = TensorInfo::new(shape, binding.dtype)
                .with_name(binding.name.clone())
                .with_layout(DataFormat::Auto)
                .allocate(&device)?;
            output.buffer().write_from_slice(&host)?;
            outputs.push(output);
        }
        Ok(outputs)
    }

    fn last_copy_count(&self) -> usize {
        self.last_copy_count
    }
}

fn create_tensorrt_backend() -> Box<dyn InferBackend> {
    Box::new(TensorRtBackend::new())
}

#[derive(Deserialize)]
#[serde(default, deny_unknown_fields)]
struct TensorRtConfig {
    device_id: Option<u32>,
    workspace_size_mb: usize,
    enable_fp16: bool,
    enable_int8: bool,
}

impl Default for TensorRtConfig {
    fn default() -> Self {
        Self {
            device_id: None,
            workspace_size_mb: 1024,
            enable_fp16: false,
            enable_int8: false,
        }
    }
}

fn configure_tensorrt(config: BackendConfig) -> Result<RuntimeOption> {
    let params: TensorRtConfig = config.parse_options("tensorrt")?;
    let model_source = config.require_model_file("TensorRT")?;
    Ok(config.into_runtime_option(
        BackendKind::TensorRt,
        model_source,
        BackendOptions::TensorRt(TensorRtOptions {
            device_id: params.device_id,
            workspace_size_mb: params.workspace_size_mb,
            enable_fp16: params.enable_fp16,
            enable_int8: params.enable_int8,
        }),
    ))
}

inventory::submit! {
    BackendDescriptor {
        kind: BackendKind::TensorRt,
        name: "tensorrt",
        create: create_tensorrt_backend,
        configure: configure_tensorrt,
    }
}

#[cfg(all(test, not(feature = "backend")))]
mod tests {
    use dg_core::{
        Buffer, BufferDesc, CpuDevice, DataFormat, DeviceKind, ExternalDropGuard, TensorDesc,
    };
    use dg_runtime::{BackendOptions, ModelSource, RuntimeOption, TensorRtOptions};

    use super::*;
    use crate::convert::{TRT_DTYPE_FLOAT, TRT_DTYPE_HALF};
    use crate::mock_sys::encode_mock_engine;

    fn mock_engine_bytes() -> Vec<u8> {
        encode_mock_engine(&[
            ("input", true, TRT_DTYPE_FLOAT, &[1, 4]),
            ("output", false, TRT_DTYPE_FLOAT, &[1, 4]),
        ])
    }

    fn runtime_option(model: Vec<u8>) -> RuntimeOption {
        RuntimeOption::new(
            BackendKind::TensorRt,
            ModelSource::Bytes(model),
            BackendOptions::TensorRt(TensorRtOptions::default()),
        )
    }

    fn f32_tensor(values: &[f32], dims: &[usize]) -> Tensor {
        let bytes: Vec<u8> = values.iter().flat_map(|v| v.to_le_bytes()).collect();
        let tensor = TensorInfo::new(Shape::new(dims.to_vec()), DataType::F32)
            .allocate(&CpuDevice::new())
            .expect("allocate tensor");
        tensor.buffer().write_from_slice(&bytes).expect("write");
        tensor
    }

    #[test]
    fn init_inspects_bindings() {
        let mut backend = TensorRtBackend::new();
        backend
            .init(&runtime_option(mock_engine_bytes()))
            .expect("init");
        assert_eq!(backend.input_count(), 1);
        assert_eq!(backend.output_count(), 1);
        let input = backend.input_info(0).expect("input info");
        assert_eq!(input.name.as_deref(), Some("input"));
        assert_eq!(input.shape.dims(), &[1, 4]);
        assert_eq!(input.dtype, DataType::F32);
        let output = backend.output_info(0).expect("output info");
        assert_eq!(output.name.as_deref(), Some("output"));
        assert_eq!(output.shape.dims(), &[1, 4]);
    }

    #[test]
    fn init_rejects_invalid_engine_bytes() {
        let mut backend = TensorRtBackend::new();
        let err = backend
            .init(&runtime_option(vec![0u8; 16]))
            .expect_err("invalid engine");
        assert!(matches!(err, Error::BackendUnavailable(_)));
    }

    #[test]
    fn init_rejects_out_of_range_device_id() {
        let mut backend = TensorRtBackend::new();
        let option = RuntimeOption::new(
            BackendKind::TensorRt,
            ModelSource::Bytes(mock_engine_bytes()),
            BackendOptions::TensorRt(TensorRtOptions {
                device_id: Some(7),
                ..TensorRtOptions::default()
            }),
        );
        assert_eq!(
            backend.init(&option),
            Err(Error::UnsupportedDevice(DeviceKind::CudaGpu))
        );
    }

    #[test]
    fn init_rejects_unsupported_precision() {
        let mut backend = TensorRtBackend::new();
        let option = runtime_option(mock_engine_bytes()).with_precision(DataType::F64);
        assert_eq!(
            backend.init(&option),
            Err(Error::UnsupportedPrecision(DataType::F64))
        );
    }

    #[test]
    fn run_round_trips_through_shim() {
        let mut backend = TensorRtBackend::new();
        backend
            .init(&runtime_option(mock_engine_bytes()))
            .expect("init");
        let input = f32_tensor(&[1.0, 2.0, 3.0, 4.0], &[1, 4]);
        let outputs = backend.run(&[input]).expect("run");
        assert_eq!(outputs.len(), 1);
        let output = &outputs[0];
        assert_eq!(output.desc().shape().dims(), &[1, 4]);
        assert_eq!(output.desc().dtype(), DataType::F32);
        let bytes = output.buffer().read_bytes();
        let values: Vec<f32> = bytes
            .chunks_exact(4)
            .map(|chunk| f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();
        assert_eq!(values, vec![1.0, 2.0, 3.0, 4.0]);
    }

    #[test]
    fn external_cuda_buffer_uses_direct_binding_without_copy() {
        let mut backend = TensorRtBackend::new();
        backend
            .init(&runtime_option(mock_engine_bytes()))
            .expect("init");

        let size = 4 * std::mem::size_of::<f32>();
        // SAFETY: the mock allocator returns an owned allocation of `size`
        // bytes, and the copy is bounded by that allocation.
        let ptr = unsafe { crate::mock_sys::trt_cuda_malloc(size) };
        assert!(!ptr.is_null());
        let values: Vec<u8> = [1.0f32, 2.0, 3.0, 4.0]
            .into_iter()
            .flat_map(f32::to_le_bytes)
            .collect();
        let ptr_value = ptr as usize;
        // SAFETY: `ptr` points to the allocation above and `values` is valid
        // for the synchronous mock copy.
        assert_eq!(
            unsafe {
                crate::mock_sys::trt_cuda_memcpy_h2d(ptr, values.as_ptr().cast(), values.len())
            },
            1
        );
        let external = Buffer::from_external(
            DeviceKind::CudaGpu,
            dg_core::MemoryDomain::CudaDevice,
            BufferDesc::new(size, 1),
            dg_core::ExternalHandle::from_raw(ptr as usize as u64),
            ExternalDropGuard::new(move || {
                // SAFETY: this is the allocation returned above and ownership
                // is released exactly once by the guard.
                unsafe { crate::mock_sys::trt_cuda_free(ptr_value as *mut std::ffi::c_void) };
            }),
        )
        .expect("external buffer");
        let tensor = Tensor::from_buffer(
            TensorDesc::new(
                Shape::new([1, 4]),
                DataType::F32,
                DataFormat::Auto,
                DeviceKind::CudaGpu,
            ),
            external,
        )
        .expect("tensor");

        let outputs = backend.run(&[tensor]).expect("run");
        assert_eq!(backend.last_copy_count(), 0);
        assert_eq!(outputs[0].buffer().read_bytes(), values);
    }

    #[test]
    fn run_rejects_wrong_dtype_and_shape() {
        let mut backend = TensorRtBackend::new();
        backend
            .init(&runtime_option(mock_engine_bytes()))
            .expect("init");

        let wrong_shape = f32_tensor(&[1.0, 2.0], &[1, 2]);
        assert!(matches!(
            backend.run(&[wrong_shape]),
            Err(Error::InvalidOption(_))
        ));

        assert!(matches!(backend.run(&[]), Err(Error::InvalidOption(_))));

        let half_engine = encode_mock_engine(&[
            ("input", true, TRT_DTYPE_HALF, &[1, 4]),
            ("output", false, TRT_DTYPE_HALF, &[1, 4]),
        ]);
        let mut half_backend = TensorRtBackend::new();
        half_backend
            .init(&runtime_option(half_engine))
            .expect("init");
        let f32_input = f32_tensor(&[1.0, 2.0, 3.0, 4.0], &[1, 4]);
        assert!(matches!(
            half_backend.run(&[f32_input]),
            Err(Error::InvalidOption(_))
        ));
    }

    #[test]
    fn dynamic_batch_resolves_output_shape() {
        let engine = encode_mock_engine(&[
            ("input", true, TRT_DTYPE_FLOAT, &[-1, 2]),
            ("output", false, TRT_DTYPE_FLOAT, &[-1, 2]),
        ]);
        let mut backend = TensorRtBackend::new();
        backend.init(&runtime_option(engine)).expect("init");

        backend
            .reshape(&[Shape::new([3usize, 2])])
            .expect("reshape");
        assert_eq!(backend.input_info(0).expect("info").shape.dims(), &[3, 2]);

        let input = f32_tensor(&[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], &[3, 2]);
        let outputs = backend.run(&[input]).expect("run");
        assert_eq!(outputs[0].desc().shape().dims(), &[3, 2]);
    }

    #[test]
    fn reshape_rejects_unresolved_output_shape() {
        let engine = encode_mock_engine(&[
            ("input", true, TRT_DTYPE_FLOAT, &[-1, 2]),
            ("output", false, TRT_DTYPE_FLOAT, &[-1, 2, -1]),
        ]);
        let mut backend = TensorRtBackend::new();
        backend.init(&runtime_option(engine)).expect("init");

        let err = backend
            .reshape(&[Shape::new([3usize, 2])])
            .expect_err("unresolved output shape");
        assert!(
            matches!(err, Error::Backend(message) if message.contains("unresolved dynamic dimension"))
        );
    }
}
